### ISSUE TITLE
json5_decode throws exceptions by default?

### ISSUE THREAD

**Issue by keithy** [colinodell/json5#8]
By default the built in json_decode() does not throw exceptions.
on the other hand json5_decode() appears to.

This ensures that it is not a direct swap.

**Comment by colinodell** [comment]
Yep, that is correct, and this behavior is documented in the README: https://github.com/colinodell/json5#exceptions

There are two reasons we do this:

1. Not throwing exceptions is an anti-pattern
2. We don't provide JSON5 replacements for `json_last_error()` and `json_last_error_msg()` - they're completely unnecessary if you throw exceptions
